[dependencies]
base = "0.11.0"
array = "https://github.com/aviate-labs/array.mo"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap"
StableBuffer = "https://github.com/canscale/StableBuffer"
itertools = "0.2.1"
tecdsa = "0.0.4"
cbor = "0.1.3"
rep-indy-hash = "0.1.1"
libsecp256k1 = "0.1.0"
http-loopback = "0.2.0"
utilities = "2.0.2"